const mongoose = require("mongoose");
const User = require("./models/User");
const bcrypt = require("bcrypt");
const Product = require("./models/Product");

mongoose.connect("mongodb://localhost:27017/bae_db");
mongoose.connection;

var users = [
  {
    email: "admin@localhost.com",
    password: "123",
    firstName: "Admin",
    lastName: "User"
  },
  {
    email: "customer@localhost.com",
    password: "123",
    firstName: "Customer",
    lastName: "User"
  }
]

var products = [
  {
    productTitle: "Nike Air Max 90",
    productBrand: "Nike",
    productSKU: "FB9657-200",
    productYear: 2024,
    productMaterials:["Leather"],
    productDescription: "A tangible legacy. Born at the intersection of art, music and culture, this champion running shoe defined the '90s. Worn by presidents, revolutionized in collabs and celebrated in rare colorways, its bold look, waffle sole and visible Nike Air cushioning ensure it remains as relevant as ever.",
    productCategories: ["Sneakers"],
    productSeasons: ["Spring"],
    productGenders: ["Men"],
    productColors: ["Olive", "Black", "White"],
    productSizes: ["40", "41", "42", "43", "44", "45", "46", "47", "48"],
    productPrice: 159.00,
    productImages: ["https://cdn-icons-png.flaticon.com/256/732/732084.png", "https://img001.prntscr.com/file/img001/eZgJdul-SEKbD7D0PTuDdQ.png"],
    productAvailability: true,
    productStock: 10
  },
  {
    productTitle: "Tommy Hilfiger Tommy Now",
    productBrand: "Tommy Hilfiger",
    productSKU: "022548407912",
    productYear: 2018,
    productMaterials:["Liquid"],
    productDescription: "None is as stylish, none as comfortable, none as proven. The Nike Air Max 90 stays true to its roots with the legendary waffle sole, stitched overlays and classic TPU accents. Fresh details give you a modern look and Max Air cushioning ensures comfort.",
    productCategories: ["Perfume"],
    productSeasons: ["Spring", "Summer"],
    productGenders: ["Men"],
    productColors: ["White", "Red", "Navy"],
    productSizes: ["100ml"],
    productPrice: 39.99,
    productImages: ["https://www.brandslex.de/img/logos/xl/t/logo-tommy-hilfiger-01.png", "https://img001.prntscr.com/file/img001/Ql9nk3giQgaQEmMRd6kQfA.png"],
    productAvailability: true,
    productStock: 3
  },
  {
    productTitle: "Adidas Superstar",
    productBrand: "Adidas",
    productSKU: "FV3284",
    productYear: 2023,
    productMaterials: ["Leather"],
    productDescription: "An iconic design that has stood the test of time, the Adidas Superstar is a classic sneaker featuring a leather upper and the signature rubber shell toe.",
    productCategories: ["Sneakers"],
    productSeasons: ["All"],
    productGenders: ["Women"],
    productColors: ["White", "Black"],
    productSizes: ["35", "36", "37", "38", "39", "40", "41"],
    productPrice: 85.00,
    productImages: ["https://i.imgur.com/mU5X66K.png", "https://img001.prntscr.com/file/img001/pz73A7yiRn2sjln9FK1H7g.jpeg"],
    productAvailability: true,
    productStock: 20
  },
  {
    productTitle: "Ray-Ban Aviator Classic",
    productBrand: "Ray-Ban",
    productSKU: "RB3025",
    productYear: 2023,
    productMaterials: ["Metal"],
    productDescription: "The Ray-Ban Aviator Classic is a timeless design that offers both style and functionality, featuring a metal frame and UV-protective lenses.",
    productCategories: ["Sunglasses"],
    productSeasons: ["Summer"],
    productGenders: ["Diverse"],
    productColors: ["Gold", "Blue"],
    productSizes: ["55mm", "58mm", "62mm"],
    productPrice: 150.00,
    productImages: ["https://cdn.iconscout.com/icon/free/png-256/free-ray-1-282334.png", "https://img001.prntscr.com/file/img001/O2QbSEeFSjKY09nOcfMuQQ.png"],
    productAvailability: true,
    productStock: 30
  },
  {
    productTitle: "Levi's 501 Original Fit Jeans",
    productBrand: "Levi's",
    productSKU: "00501-0000",
    productYear: 2024,
    productMaterials: ["Denim"],
    productDescription: "The Levi's 501 Original Fit Jeans are a staple in any wardrobe, offering a classic straight fit and durable denim construction.",
    productCategories: ["Clothing"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["Blue"],
    productSizes: ["28x30", "30x32", "32x34", "34x36"],
    productPrice: 60.00,
    productImages: ["https://cdn.iconscout.com/icon/free/png-256/free-levis-2-202638.png", "https://img001.prntscr.com/file/img001/M2DSSHrUS92rYD8LlkuMgg.png"],
    productAvailability: true,
    productStock: 25
  },
  {
    productTitle: "Versace Medusa Chain Reaction",
    productBrand: "Versace",
    productSKU: "DSU7061-DVIT2T_D41OH",
    productYear: 2024,
    productMaterials: ["Leather", "Mesh"],
    productDescription: "Versace Medusa Chain Reaction Sneakers feature a chunky sole and iconic Medusa head detailing, offering a bold and unique style.",
    productCategories: ["Sneakers"],
    productSeasons: ["Spring", "Summer"],
    productGenders: ["Men"],
    productColors: ["White", "Gold"],
    productSizes: ["40", "41", "42", "43", "44", "45"],
    productPrice: 1095.00,
    productImages: ["https://cdn.iconscout.com/icon/free/png-256/free-versace-1-202706.png", "https://img001.prntscr.com/file/img001/AmSoU7deRaiC8e9AR4oRPw.png"],
    productAvailability: true,
    productStock: 8
  },
  {
    productTitle: "Ralph Lauren Polo Shirt",
    productBrand: "Ralph Lauren",
    productSKU: "710680254001",
    productYear: 2024,
    productMaterials: ["Cotton"],
    productDescription: "The Ralph Lauren Polo Shirt is a timeless classic, featuring a comfortable cotton fabric and the iconic polo player logo.",
    productCategories: ["Shirts"],
    productSeasons: ["Spring", "Summer"],
    productGenders: ["Men"],
    productColors: ["Navy", "White", "Red", "Green"],
    productSizes: ["S", "M", "L", "XL", "XXL"],
    productPrice: 95.00,
    productImages: ["https://img001.prntscr.com/file/img001/x8JyuuZRT5WZgE8ig9XyHA.jpg", "https://img001.prntscr.com/file/img001/zj8GJr6gRQysWo-NAQNzHg.png"],
    productAvailability: true,
    productStock: 25
  },
  {
    productTitle: "Tommy Hilfiger Puffer Jacket",
    productBrand: "Tommy Hilfiger",
    productSKU: "TT0TT10123",
    productYear: 2024,
    productMaterials: ["Polyester"],
    productDescription: "The Tommy Hilfiger Essential Puffer Jacket provides warmth and style with its lightweight padding and signature Tommy Hilfiger logo.",
    productCategories: ["Jackets"],
    productSeasons: ["Winter"],
    productGenders: ["Boys"],
    productColors: ["Black"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 120.00,
    productImages: ["https://www.brandslex.de/img/logos/xl/t/logo-tommy-hilfiger-01.png", "https://img001.prntscr.com/file/img001/dkXXQXKFQwyGAmmGxAXZ4g.png"],
    productAvailability: true,
    productStock: 15
  },
  {
    productTitle: "Lacoste Classic Polo Shirt",
    productBrand: "Lacoste",
    productSKU: "L1212",
    productYear: 2024,
    productMaterials: ["Cotton"],
    productDescription: "The Lacoste Classic Polo Shirt is made from high-quality cotton and features the iconic crocodile logo on the chest.",
    productCategories: ["Shirts"],
    productSeasons: ["Spring", "Summer"],
    productGenders: ["Men"],
    productColors: ["White", "Navy", "Green", "Red"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 85.00,
    productImages: ["https://img001.prntscr.com/file/img001/pwUb1pxMTNyKkNbOOzVzKQ.png", "https://img001.prntscr.com/file/img001/BkdmypygQeavwcpRFSEdgw.png"],
    productAvailability: true,
    productStock: 20
  },
  {
    productTitle: "Gant Original Hoodie",
    productBrand: "Gant",
    productSKU: "2046084",
    productYear: 2024,
    productMaterials: ["Cotton"],
    productDescription: "The Gant Original Hoodie is comfortable and stylish, featuring a drawstring hood and the Gant logo on the chest.",
    productCategories: ["Hoodies"],
    productSeasons: ["Autumn", "Winter"],
    productGenders: ["Women"],
    productColors: ["Grey", "Black"],
    productSizes: ["XS", "S", "M", "L"],
    productPrice: 90.00,
    productImages: ["https://img001.prntscr.com/file/img001/fu834qnmSnS8S7UObbyp1w.jpg", "https://img001.prntscr.com/file/img001/druW5JMbR_udkReQF8NlOg.png"],
    productAvailability: true,
    productStock: 10
  },
  {
    productTitle: "Guess 1981 Eau de Toilette",
    productBrand: "Guess",
    productSKU: "85715320401",
    productYear: 2024,
    productMaterials: ["Liquid"],
    productDescription: "Guess 1981 is a fresh and elegant fragrance for women, combining floral and woody notes.",
    productCategories: ["Perfume"],
    productSeasons: ["All"],
    productGenders: ["Women"],
    productColors: ["Clear"],
    productSizes: ["50ml", "100ml"],
    productPrice: 45.00,
    productImages: ["https://img001.prntscr.com/file/img001/DOWZuEqISxSdeaVTkFHdRQ.jpg", "https://img001.prntscr.com/file/img001/PZpm_1WIRDK3034zN_Iwtw.png"],
    productAvailability: true,
    productStock: 25
  },
  {
    productTitle: "Michael Kors Jet Set Large Tote",
    productBrand: "Michael Kors",
    productSKU: "30T0GJBT7B",
    productYear: 2024,
    productMaterials: ["Canvas", "Leather"],
    productDescription: "The Michael Kors Jet Set Large Tote is practical and stylish, featuring a spacious interior and the signature MK logo.",
    productCategories: ["Bags"],
    productSeasons: ["All"],
    productGenders: ["Women"],
    productColors: ["Brown", "Black"],
    productSizes: ["One Size"],
    productPrice: 150.00,
    productImages: ["https://img001.prntscr.com/file/img001/gxmgDH1wQ8S4fGWSNtj4RA.png", "https://img001.prntscr.com/file/img001/5hLO7e6JTuikJandWAlMRQ.png"],
    productAvailability: true,
    productStock: 12
  },
   {
    productTitle: "Nike Air Max 90 GORE-TEX",
    productBrand: "Nike",
    productSKU: "FD5810-101",
    productYear: 2024,
    productMaterials:["Leather"],
    productDescription: "A tangible legacy. These AM90s will accompany you on all your adventures thanks to a mix of GORE-TEX and mesh materials. They have been worn by presidents, revolutionized in collaborations and celebrated with rare colorways. The waffle sole, the eye-catching look and the Nike Air cushioning keep it alive.",
    productCategories: ["Sneakers"],
    productSeasons: ["Winter"],
    productGenders: ["Diverse"],
    productColors: ["White", "Crimson", "Black", "Grey"],
    productSizes: ["38.5", "39", "40", "40.5", "41", "42", "42.5", "43", "44", "44.5", "45", "45.5", "46", "47", "47.5", "48.5", "49.5"],
    productPrice: 179.99,
    productImages: ["https://cdn-icons-png.flaticon.com/256/732/732084.png", "https://img001.prntscr.com/file/img001/gEqhDnLXQry_YwyXrn96cg.png"],
    productAvailability: false,
    productStock: 0
  },
  {
    productTitle: "Polo Ralph Lauren Classic Fit",
    productBrand: "Polo Ralph Lauren",
    productSKU: "710548216001",
    productYear: 2024,
    productMaterials: ["Cotton"],
    productDescription: "The Polo Ralph Lauren Classic Fit Polo is a versatile and timeless piece, featuring the signature pony logo on the chest.",
    productCategories: ["Shirts"],
    productSeasons: ["Spring", "Summer"],
    productGenders: ["Men"],
    productColors: ["Blue", "White", "Red", "Green"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 95.00,
    productImages: ["https://img001.prntscr.com/file/img001/x8JyuuZRT5WZgE8ig9XyHA.jpg", "https://img001.prntscr.com/file/img001/VOZ0QNXnRoCFZmPg965z2g.png"],
    productAvailability: true,
    productStock: 30
  },
  {
    productTitle: "Timberland Waterproof Boots",
    productBrand: "Timberland",
    productSKU: "TB010073713",
    productYear: 2024,
    productMaterials: ["Leather"],
    productDescription: "The Timberland 6-Inch Premium Waterproof Boots are durable and stylish, perfect for all-weather conditions.",
    productCategories: ["Boots"],
    productSeasons: ["Autumn", "Winter"],
    productGenders: ["Men"],
    productColors: ["Wheat", "Black"],
    productSizes: ["40", "41", "42", "43", "44", "45"],
    productPrice: 170.00,
    productImages: ["https://img001.prntscr.com/file/img001/tOCTv1h9RN-FpNV3XPRCqA.jpg", "https://img001.prntscr.com/file/img001/yDVNd9h_QZW32eDYeIbGCw.png"],
    productAvailability: true,
    productStock: 20
  },
  {
    productTitle: "Converse Chuck Taylor All Star",
    productBrand: "Converse",
    productSKU: "M9160",
    productYear: 2024,
    productMaterials: ["Canvas"],
    productDescription: "The Converse Chuck Taylor All Star is an iconic sneaker with a classic design and versatile style.",
    productCategories: ["Sneakers"],
    productSeasons: ["All"],
    productGenders: ["Diverse"],
    productColors: ["Black", "White"],
    productSizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
    productPrice: 60.00,
    productImages: ["https://img001.prntscr.com/file/img001/uRrTNiDYTKKjasEKLcwbyw.png", "https://img001.prntscr.com/file/img001/_6Ri_MBQR4qwIO1RHgxm0A.png"],
    productAvailability: true,
    productStock: 50
  },
  {
    productTitle: "Under Armour Tech 2.0 T-Shirt",
    productBrand: "Under Armour",
    productSKU: "1326413",
    productYear: 2024,
    productMaterials: ["Polyester"],
    productDescription: "The Under Armour Tech 2.0 T-Shirt is lightweight and breathable, designed for optimal performance during workouts.",
    productCategories: ["T-Shirts"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["Black", "Grey", "Red", "Blue"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 25.00,
    productImages: ["https://img001.prntscr.com/file/img001/qwfgQ50fR66CK7pceVm_0w.png", "https://img001.prntscr.com/file/img001/6dNCIhMXQr2VJdhZKzyo0w.png"],
    productAvailability: true,
    productStock: 40
  },
  {
    productTitle: "Puma Suede Classic",
    productBrand: "Puma",
    productSKU: "352634",
    productYear: 2024,
    productMaterials: ["Suede"],
    productDescription: "The Puma Suede Classic is a timeless sneaker with a durable suede upper and comfortable fit.",
    productCategories: ["Sneakers"],
    productSeasons: ["All"],
    productGenders: ["Diverse"],
    productColors: ["Black", "Blue", "Red", "Green"],
    productSizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
    productPrice: 70.00,
    productImages: ["https://img001.prntscr.com/file/img001/ZxxUZMHzRvGqUYuFfhnK-g.jpg", "https://img001.prntscr.com/file/img001/9z3V26DcTdKoqPGa683mvA.png"],
    productAvailability: true,
    productStock: 35
  },
  {
    productTitle: "Jack Wolfskin Knit Cap",
    productBrand: "Jack Wolfskin",
    productSKU: "1907141",
    productYear: 2024,
    productMaterials: ["Acrylic"],
    productDescription: "The Jack Wolfskin Stormlock Knit Cap is warm and windproof, perfect for outdoor activities in cold weather.",
    productCategories: ["Hats"],
    productSeasons: ["Winter"],
    productGenders: ["Diverse"],
    productColors: ["Black", "Grey", "Blue"],
    productSizes: ["One Size"],
    productPrice: 30.00,
    productImages: ["https://img001.prntscr.com/file/img001/md_uuu2PQFqNxNu_ztip1g.png", "https://img001.prntscr.com/file/img001/OcBFs4rWTYqw-sAsAwZw9w.png"],
    productAvailability: true,
    productStock: 25
  },
  {
    productTitle: "The North Face Backpack",
    productBrand: "The North Face",
    productSKU: "NF0A52ST",
    productYear: 2024,
    productMaterials: ["Nylon"],
    productDescription: "The North Face Borealis Bkpk is versatile and durable, featuring multiple compartments and comfortable straps for everyday use.",
    productCategories: ["Backpacks"],
    productSeasons: ["All"],
    productGenders: ["Diverse"],
    productColors: ["Black", "Yellow"],
    productSizes: ["One Size"],
    productPrice: 89.00,
    productImages: ["https://img001.prntscr.com/file/img001/IdQye7wOQO2tdOSMW4afRw.png", "https://img001.prntscr.com/file/img001/9GA-QxZaRLqD7aAIdxwnow.png"],
    productAvailability: true,
    productStock: 20
  },
  {
    productTitle: "Gant Classic Chino Pants",
    productBrand: "Gant",
    productSKU: "1505149",
    productYear: 2024,
    productMaterials: ["Cotton"],
    productDescription: "The Gant Classic Chino Pants are versatile and comfortable, suitable for both casual and smart-casual outfits.",
    productCategories: ["Pants"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["Beige", "Navy", "Black"],
    productSizes: ["30", "32", "34", "36", "38"],
    productPrice: 100.00,
    productImages: ["https://img001.prntscr.com/file/img001/fu834qnmSnS8S7UObbyp1w.jpg", "https://img001.prntscr.com/file/img001/Jk48cjvrTOuVsdmaeRxWVg.png"],
    productAvailability: true,
    productStock: 15
  },
  {
    productTitle: "Lacoste L.12.12 Blanc EDT",
    productBrand: "Lacoste",
    productSKU: "737052413068",
    productYear: 2024,
    productMaterials: ["Liquid"],
    productDescription: "Lacoste L.12.12 Blanc is a fresh and sporty fragrance for men, combining citrus and woody notes.",
    productCategories: ["Perfume"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["Clear"],
    productSizes: ["50ml", "100ml"],
    productPrice: 65.00,
    productImages: ["https://img001.prntscr.com/file/img001/pwUb1pxMTNyKkNbOOzVzKQ.png", "https://img001.prntscr.com/file/img001/bV5445pXQsiZnew2Vpt5Fw.png"],
    productAvailability: true,
    productStock: 20
  },
  {
    productTitle: "Tommy Hilfiger Backpack",
    productBrand: "Tommy Hilfiger",
    productSKU: "AM0AM07425",
    productYear: 2024,
    productMaterials: ["Polyester"],
    productDescription: "The Tommy Hilfiger Modern Essentials Backpack is stylish and functional, featuring multiple compartments and the signature Tommy logo.",
    productCategories: ["Backpacks"],
    productSeasons: ["All"],
    productGenders: ["Diverse"],
    productColors: ["Navy", "Black"],
    productSizes: ["One Size"],
    productPrice: 80.00,
    productImages: ["https://www.brandslex.de/img/logos/xl/t/logo-tommy-hilfiger-01.png", "https://img001.prntscr.com/file/img001/z95ydE59Q_O7M9trEcwBvQ.png"],
    productAvailability: true,
    productStock: 20
  },
  {
    productTitle: "Guess Denim Jacket",
    productBrand: "Guess",
    productSKU: "M92N19D3Y11",
    productYear: 2024,
    productMaterials: ["Denim"],
    productDescription: "The Guess Denim Jacket is a stylish piece with a vintage look, perfect for casual outfits.",
    productCategories: ["Jackets"],
    productSeasons: ["Spring", "Autumn"],
    productGenders: ["Women"],
    productColors: ["Blue"],
    productSizes: ["XS", "S", "M", "L"],
    productPrice: 110.00,
    productImages: ["https://img001.prntscr.com/file/img001/DOWZuEqISxSdeaVTkFHdRQ.jpg", "https://img001.prntscr.com/file/img001/M9J2DPJHRp-WWhw8F3SpJA.png"],
    productAvailability: true,
    productStock: 10
  },
  {
    productTitle: "Michael Kors Parker SS Watch",
    productBrand: "Michael Kors",
    productSKU: "MK5896",
    productYear: 2024,
    productMaterials: ["Stainless Steel"],
    productDescription: "The Michael Kors Parker Watch combines elegance and functionality, featuring a stainless steel case and crystal accents.",
    productCategories: ["Watches"],
    productSeasons: ["All"],
    productGenders: ["Women"],
    productColors: ["Rose Gold"],
    productSizes: ["One Size"],
    productPrice: 195.00,
    productImages: ["https://img001.prntscr.com/file/img001/gxmgDH1wQ8S4fGWSNtj4RA.png", "https://img001.prntscr.com/file/img001/aEbFLvuSS8SWMfsv4_pVzg.png"],
    productAvailability: true,
    productStock: 15
  },
  {
    productTitle: "Polo Ralph Lauren Oxford Shirt",
    productBrand: "Polo Ralph Lauren",
    productSKU: "710548733003",
    productYear: 2024,
    productMaterials: ["Cotton"],
    productDescription: "The Polo Ralph Lauren Oxford Shirt is a wardrobe staple, featuring a classic fit and the iconic pony logo.",
    productCategories: ["Shirts"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["White", "Blue", "Pink"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 90.00,
    productImages: ["https://img001.prntscr.com/file/img001/x8JyuuZRT5WZgE8ig9XyHA.jpg", "https://img001.prntscr.com/file/img001/H7t8Uqi8RqiY7H8vu7LSuw.png"],
    productAvailability: true,
    productStock: 25
  },
  {
    productTitle: "Nike Air Max 90",
    productBrand: "Nike",
    productSKU: "DH8010-103",
    productYear: 2024,
    productMaterials:["Leather"],
    productDescription: "None is as stylish, none as comfortable, none as proven. The Nike Air Max 90 stays true to its roots with the legendary waffle sole, stitched overlays and classic TPU accents. Fresh details give you a modern look and Max Air cushioning ensures comfort.",
    productCategories: ["Sneakers"],
    productSeasons: ["Winter"],
    productGenders: ["Women"],
    productColors: ["White", "Lilac", "Grey"],
    productSizes: ["35.5", "36", "36.5", "37.5", "38", "38.5", "39", "40", "40.5", "41", "42", "42.5", "43", "44", "44.5"],
    productPrice: 159.99,
    productImages: ["https://cdn-icons-png.flaticon.com/256/732/732084.png", "https://img001.prntscr.com/file/img001/gl7ezTpNTIixEhLiM8IkDg.png"],
    productAvailability: true,
    productStock: 5
  },
  {
    productTitle: "Timberland Classic Leather Belt",
    productBrand: "Timberland",
    productSKU: "B75493",
    productYear: 2024,
    productMaterials: ["Leather"],
    productDescription: "The Timberland Classic Leather Belt is durable and stylish, perfect for both casual and formal outfits.",
    productCategories: ["Accessories"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["Brown", "Black"],
    productSizes: ["32", "34", "36", "38", "40"],
    productPrice: 40.00,
    productImages: ["https://img001.prntscr.com/file/img001/tOCTv1h9RN-FpNV3XPRCqA.jpg", "https://img001.prntscr.com/file/img001/XUc1LTJARwGbf_Ca90Ky8Q.png"],
    productAvailability: true,
    productStock: 30
  },
  {
    productTitle: "Converse Chuck 70 High Top",
    productBrand: "Converse",
    productSKU: "162050C",
    productYear: 2024,
    productMaterials: ["Canvas"],
    productDescription: "The Converse Chuck 70 High Top offers a vintage-inspired design with modern comfort and durability.",
    productCategories: ["Sneakers"],
    productSeasons: ["All"],
    productGenders: ["Diverse"],
    productColors: ["Black", "White"],
    productSizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
    productPrice: 85.00,
    productImages: ["https://img001.prntscr.com/file/img001/uRrTNiDYTKKjasEKLcwbyw.png", "https://img001.prntscr.com/file/img001/ni7A4A1IQ6utpvCOl5Ytnw.png"],
    productAvailability: true,
    productStock: 45
  },
  {
    productTitle: "Under Armour Fleece Hoodie",
    productBrand: "Under Armour",
    productSKU: "1357031",
    productYear: 2024,
    productMaterials: ["Polyester"],
    productDescription: "The Under Armour Storm Fleece Hoodie is water-resistant and comfortable, perfect for outdoor activities.",
    productCategories: ["Hoodies"],
    productSeasons: ["Autumn", "Winter"],
    productGenders: ["Men"],
    productColors: ["Black", "Grey"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 75.00,
    productImages: ["https://img001.prntscr.com/file/img001/qwfgQ50fR66CK7pceVm_0w.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 20
  },
  {
    productTitle: "Puma Essentials Logo Tee",
    productBrand: "Puma",
    productSKU: "586672",
    productYear: 2024,
    productMaterials: ["Cotton"],
    productDescription: "The Puma Essentials Logo Tee is a comfortable and stylish option for casual wear, featuring the Puma logo on the chest.",
    productCategories: ["T-Shirts"],
    productSeasons: ["All"],
    productGenders: ["Women"],
    productColors: ["White", "Black", "Pink"],
    productSizes: ["XS", "S", "M", "L"],
    productPrice: 25.00,
    productImages: ["https://img001.prntscr.com/file/img001/ZxxUZMHzRvGqUYuFfhnK-g.jpg", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 30
  },
  {
    productTitle: "Jack Wolfskin Helium Jacket",
    productBrand: "Jack Wolfskin",
    productSKU: "1204342",
    productYear: 2024,
    productMaterials: ["Polyester"],
    productDescription: "The Jack Wolfskin Helium Jacket is lightweight and warm, featuring a windproof and water-repellent design.",
    productCategories: ["Jackets"],
    productSeasons: ["Winter"],
    productGenders: ["Diverse"],
    productColors: ["Black", "Blue", "Green"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 130.00,
    productImages: ["https://img001.prntscr.com/file/img001/md_uuu2PQFqNxNu_ztip1g.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 18
  },
  {
    productTitle: "Adidas Ultraboost 21",
    productBrand: "Adidas",
    productSKU: "FY0372",
    productYear: 2024,
    productMaterials: ["Synthetic", "Textile"],
    productDescription: "The Adidas Ultraboost 21 is designed for maximum comfort and performance, featuring a responsive Boost midsole and a supportive Primeknit upper.",
    productCategories: ["Running Shoes"],
    productSeasons: ["Summer"],
    productGenders: ["Men"],
    productColors: ["Black", "White", "Blue"],
    productSizes: ["40", "41", "42", "43", "44", "45"],
    productPrice: 180.00,
    productImages: ["https://i.imgur.com/mU5X66K.png", "https://img001.prntscr.com/file/img001/tNIMsoTtSWqbRhlibvEi_Q.png"],
    productAvailability: true,
    productStock: 15
  },
  {
    productTitle: "The North Face Resolve 2 Jacket",
    productBrand: "The North Face",
    productSKU: "NF0A2VD5",
    productYear: 2024,
    productMaterials: ["Nylon"],
    productDescription: "The North Face Resolve 2 Jacket is waterproof and breathable, designed for outdoor adventures in all weather conditions.",
    productCategories: ["Jackets"],
    productSeasons: ["Spring", "Autumn"],
    productGenders: ["Men"],
    productColors: ["Black", "Grey", "Red"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 99.00,
    productImages: ["https://img001.prntscr.com/file/img001/IdQye7wOQO2tdOSMW4afRw.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 15
  },
  {
    productTitle: "Gant Original Slim Fit Jeans",
    productBrand: "Gant",
    productSKU: "10000248",
    productYear: 2024,
    productMaterials: ["Denim"],
    productDescription: "The Gant Original Slim Fit Jeans offer a modern silhouette with a comfortable fit, made from high-quality denim.",
    productCategories: ["Jeans"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["Blue", "Black"],
    productSizes: ["30", "32", "34", "36", "38"],
    productPrice: 120.00,
    productImages: ["https://img001.prntscr.com/file/img001/fu834qnmSnS8S7UObbyp1w.jpg", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 25
  },
  {
    productTitle: "Hugo Boss Regular Fit Polo Shirt",
    productBrand: "Hugo Boss",
    productSKU: "50470952",
    productYear: 2024,
    productMaterials: ["Cotton"],
    productDescription: "The Hugo Boss Regular Fit Polo Shirt offers a classic look with a comfortable fit and the iconic Hugo Boss logo.",
    productCategories: ["Shirts"],
    productSeasons: ["Spring", "Summer"],
    productGenders: ["Men"],
    productColors: ["White", "Black", "Blue"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 110.00,
    productImages: ["https://img001.prntscr.com/file/img001/jpUNBbcWQeKfi69cQNK9mw.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 20
  },
  {
    productTitle: "Adidas Originals Trefoil Hoodie",
    productBrand: "Adidas",
    productSKU: "FM3307",
    productYear: 2024,
    productMaterials: ["Cotton", "Polyester"],
    productDescription: "The Adidas Originals Trefoil Hoodie features the classic Trefoil logo and is made from soft, cozy materials.",
    productCategories: ["Hoodies"],
    productSeasons: ["Autumn", "Winter"],
    productGenders: ["Men"],
    productColors: ["Black", "Grey", "Red"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 75.00,
    productImages: ["https://i.imgur.com/mU5X66K.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 30
  },
  {
    productTitle: "Puma Essentials Logo T-Shirt",
    productBrand: "Puma",
    productSKU: "586673",
    productYear: 2024,
    productMaterials: ["Cotton"],
    productDescription: "The Puma Essentials Logo T-Shirt is a comfortable and stylish option for casual wear, featuring the Puma logo on the chest.",
    productCategories: ["T-Shirts"],
    productSeasons: ["All"],
    productGenders: ["Women"],
    productColors: ["White", "Black", "Pink"],
    productSizes: ["XS", "S", "M", "L"],
    productPrice: 25.00,
    productImages: ["https://img001.prntscr.com/file/img001/ZxxUZMHzRvGqUYuFfhnK-g.jpg", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 30
  },
  {
    productTitle: "The North Face Bkpk 2.0",
    productBrand: "The North Face",
    productSKU: "NF0A52SU",
    productYear: 2024,
    productMaterials: ["Nylon"],
    productDescription: "The North Face Borealis Backpack is versatile and durable, featuring multiple compartments and comfortable straps for everyday use.",
    productCategories: ["Backpacks"],
    productSeasons: ["All"],
    productGenders: ["Diverse"],
    productColors: ["Black", "Red", "Blue"],
    productSizes: ["One Size"],
    productPrice: 89.00,
    productImages: ["https://img001.prntscr.com/file/img001/IdQye7wOQO2tdOSMW4afRw.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 20
  },
  {
    productTitle: "Gant Classic Chino Pants",
    productBrand: "Gant",
    productSKU: "1505148",
    productYear: 2024,
    productMaterials: ["Cotton"],
    productDescription: "The Gant Classic Chino Pants are versatile and comfortable, suitable for both casual and smart-casual outfits.",
    productCategories: ["Pants"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["Beige", "Navy", "Black"],
    productSizes: ["30", "32", "34", "36", "38"],
    productPrice: 100.00,
    productImages: ["https://img001.prntscr.com/file/img001/fu834qnmSnS8S7UObbyp1w.jpg", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 15
  },
  {
    productTitle: "Guess Denim Jacket",
    productBrand: "Guess",
    productSKU: "M92N19D3Y12",
    productYear: 2024,
    productMaterials: ["Denim"],
    productDescription: "The Guess Denim Jacket is a stylish piece with a vintage look, perfect for casual outfits.",
    productCategories: ["Jackets"],
    productSeasons: ["Spring", "Autumn"],
    productGenders: ["Women"],
    productColors: ["Blue"],
    productSizes: ["XS", "S", "M", "L"],
    productPrice: 110.00,
    productImages: ["https://img001.prntscr.com/file/img001/DOWZuEqISxSdeaVTkFHdRQ.jpg", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 10
  },
  {
    productTitle: "Polo Ralph Lauren Oxford Shirt",
    productBrand: "Polo Ralph Lauren",
    productSKU: "710548733004",
    productYear: 2024,
    productMaterials: ["Cotton"],
    productDescription: "The Polo Ralph Lauren Oxford Shirt is a wardrobe staple, featuring a classic fit and the iconic pony logo.",
    productCategories: ["Shirts"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["White", "Blue", "Pink"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 90.00,
    productImages: ["https://img001.prntscr.com/file/img001/x8JyuuZRT5WZgE8ig9XyHA.jpg", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 25
  },
  {
    productTitle: "Timberland Classic Leather Belt",
    productBrand: "Timberland",
    productSKU: "B75494",
    productYear: 2024,
    productMaterials: ["Leather"],
    productDescription: "The Timberland Classic Leather Belt is durable and stylish, perfect for both casual and formal outfits.",
    productCategories: ["Accessories"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["Brown", "Black"],
    productSizes: ["32", "34", "36", "38", "40"],
    productPrice: 40.00,
    productImages: ["https://img001.prntscr.com/file/img001/tOCTv1h9RN-FpNV3XPRCqA.jpg", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 30
  },
  {
    productTitle: "Converse Chuck 70 High Top",
    productBrand: "Converse",
    productSKU: "162051C",
    productYear: 2024,
    productMaterials: ["Canvas"],
    productDescription: "The Converse Chuck 70 High Top offers a vintage-inspired design with modern comfort and durability.",
    productCategories: ["Sneakers"],
    productSeasons: ["All"],
    productGenders: ["Diverse"],
    productColors: ["Black", "White"],
    productSizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
    productPrice: 85.00,
    productImages: ["https://img001.prntscr.com/file/img001/uRrTNiDYTKKjasEKLcwbyw.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 45
  },
  {
    productTitle: "Puma Essentials Logo Tee",
    productBrand: "Puma",
    productSKU: "586674",
    productYear: 2024,
    productMaterials: ["Cotton"],
    productDescription: "The Puma Essentials Logo Tee is a comfortable and stylish option for casual wear, featuring the Puma logo on the chest.",
    productCategories: ["T-Shirts"],
    productSeasons: ["All"],
    productGenders: ["Women"],
    productColors: ["White", "Black", "Pink"],
    productSizes: ["XS", "S", "M", "L"],
    productPrice: 25.00,
    productImages: ["https://img001.prntscr.com/file/img001/ZxxUZMHzRvGqUYuFfhnK-g.jpg", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 30
  },
  {
    productTitle: "Jack Wolfskin Helium Jacket",
    productBrand: "Jack Wolfskin",
    productSKU: "1204343",
    productYear: 2024,
    productMaterials: ["Polyester"],
    productDescription: "The Jack Wolfskin Helium Jacket is lightweight and warm, featuring a windproof and water-repellent design.",
    productCategories: ["Jackets"],
    productSeasons: ["Winter"],
    productGenders: ["Diverse"],
    productColors: ["Black", "Blue", "Green"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 130.00,
    productImages: ["https://img001.prntscr.com/file/img001/md_uuu2PQFqNxNu_ztip1g.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 18
  },
  {
    productTitle: "The North Face Resolve 2 Jacket",
    productBrand: "The North Face",
    productSKU: "NF0A2VD6",
    productYear: 2024,
    productMaterials: ["Nylon"],
    productDescription: "The North Face Resolve 2 Jacket is waterproof and breathable, designed for outdoor adventures in all weather conditions.",
    productCategories: ["Jackets"],
    productSeasons: ["Spring", "Autumn"],
    productGenders: ["Men"],
    productColors: ["Black", "Grey", "Red"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 99.00,
    productImages: ["https://img001.prntscr.com/file/img001/IdQye7wOQO2tdOSMW4afRw.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 15
  },
  {
    productTitle: "Gant Original Slim Fit Jeans",
    productBrand: "Gant",
    productSKU: "10000249",
    productYear: 2024,
    productMaterials: ["Denim"],
    productDescription: "The Gant Original Slim Fit Jeans offer a modern silhouette with a comfortable fit, made from high-quality denim.",
    productCategories: ["Jeans"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["Blue", "Black"],
    productSizes: ["30", "32", "34", "36", "38"],
    productPrice: 120.00,
    productImages: ["https://img001.prntscr.com/file/img001/fu834qnmSnS8S7UObbyp1w.jpg", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 25
  },
  {
    productTitle: "Tommy Hilfiger Light Jacket",
    productBrand: "Tommy Hilfiger",
    productSKU: "TT0TT10068",
    productYear: 2024,
    productMaterials: ["Polyester"],
    productDescription: "This lightweight quilted jacket from Tommy Hilfiger is perfect for the transitional seasons, offering warmth without the bulk.",
    productCategories: ["Jackets"],
    productSeasons: ["Spring", "Autumn"],
    productGenders: ["Men"],
    productColors: ["Navy", "Black"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 140.00,
    productImages: ["https://www.brandslex.de/img/logos/xl/t/logo-tommy-hilfiger-01.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 12
  },
  {
    productTitle: "Adidas AC Classics Pants",
    productBrand: "Adidas",
    productSKU: "GN2792",
    productYear: 2024,
    productMaterials: ["Polyester"],
    productDescription: "Adidas Adicolor Classics 3-Stripes Pants are designed for comfort and style, featuring the iconic 3-stripes down the sides.",
    productCategories: ["Pants"],
    productSeasons: ["All"],
    productGenders: ["Diverse"],
    productColors: ["Black", "Blue", "Red"],
    productSizes: ["XS", "S", "M", "L", "XL"],
    productPrice: 60.00,
    productImages: ["https://i.imgur.com/mU5X66K.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 30
  },
  {
    productTitle: "Lacoste Chaymon Trainers",
    productBrand: "Lacoste",
    productSKU: "737CMA0017",
    productYear: 2024,
    productMaterials: ["Leather"],
    productDescription: "The Lacoste Chaymon Trainers combine classic design with contemporary style, featuring leather uppers and the signature crocodile logo.",
    productCategories: ["Sneakers"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["White", "Black", "Navy"],
    productSizes: ["40", "41", "42", "43", "44", "45"],
    productPrice: 120.00,
    productImages: ["https://img001.prntscr.com/file/img001/pwUb1pxMTNyKkNbOOzVzKQ.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 20
  },
  {
    productTitle: "Levi's HR Skinny Jeans",
    productBrand: "Levi's",
    productSKU: "188820090",
    productYear: 2024,
    productMaterials: ["Denim"],
    productDescription: "Levi's 721 High Rise Skinny Jeans offer a flattering fit and are made from stretch denim for comfort and style.",
    productCategories: ["Jeans"],
    productSeasons: ["All"],
    productGenders: ["Women"],
    productColors: ["Blue", "Black"],
    productSizes: ["24", "25", "26", "27", "28", "29", "30"],
    productPrice: 98.00,
    productImages: ["https://cdn.iconscout.com/icon/free/png-256/free-levis-2-202638.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 18
  },
  {
    productTitle: "Superdry Vintage Logo Hoodie",
    productBrand: "Superdry",
    productSKU: "M2010286A",
    productYear: 2024,
    productMaterials: ["Cotton", "Polyester"],
    productDescription: "The Superdry Vintage Logo Hoodie offers a comfortable fit and features the iconic Superdry logo on the chest.",
    productCategories: ["Hoodies"],
    productSeasons: ["Autumn", "Winter"],
    productGenders: ["Men"],
    productColors: ["Navy", "Grey", "Black"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 75.00,
    productImages: ["https://img001.prntscr.com/file/img001/m-oBnHY3SGWQMA2O_8fFYA.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 20
  },
  {
    productTitle: "Mango Trench Coat",
    productBrand: "Mango",
    productSKU: "77051867",
    productYear: 2024,
    productMaterials: ["Cotton", "Polyester"],
    productDescription: "The Mango Cotton-Blend Trench Coat is a timeless piece that offers a chic and elegant look, perfect for transitional weather.",
    productCategories: ["Coats"],
    productSeasons: ["Spring", "Autumn"],
    productGenders: ["Women"],
    productColors: ["Beige", "Black"],
    productSizes: ["XS", "S", "M", "L"],
    productPrice: 130.00,
    productImages: ["https://img001.prntscr.com/file/img001/u9p31FVpRoiMFKzBF7Zryw.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 10
  },
  {
    productTitle: "Esprit Regular Fit Jeans",
    productBrand: "Esprit",
    productSKU: "990EE2B304",
    productYear: 2024,
    productMaterials: ["Denim"],
    productDescription: "Esprit Regular Fit Jeans are made from high-quality denim and offer a comfortable fit with a classic design.",
    productCategories: ["Jeans"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["Blue", "Black"],
    productSizes: ["30", "32", "34", "36", "38"],
    productPrice: 75.00,
    productImages: ["https://img001.prntscr.com/file/img001/GbsXwKWYS5GiJrlSot3cSg.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 20
  },
  {
    productTitle: "Fossil Jacqueline Watch",
    productBrand: "Fossil",
    productSKU: "ES4368",
    productYear: 2024,
    productMaterials: ["Stainless Steel"],
    productDescription: "The Fossil Jacqueline Watch features a classic design with a stainless steel case and leather strap, perfect for any occasion.",
    productCategories: ["Watches"],
    productSeasons: ["All"],
    productGenders: ["Women"],
    productColors: ["Rose Gold", "Silver"],
    productSizes: ["One Size"],
    productPrice: 120.00,
    productImages: ["https://img001.prntscr.com/file/img001/ItkF74XiTfmDDdq5YIdU1w.jpg", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 15
  },
  {
    productTitle: "H&M Slim Fit Blazer",
    productBrand: "H&M",
    productSKU: "0873260010",
    productYear: 2024,
    productMaterials: ["Polyester", "Viscose"],
    productDescription: "The H&M Slim Fit Blazer offers a sleek and stylish look, perfect for formal and semi-formal occasions.",
    productCategories: ["Blazers"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["Black", "Navy"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 70.00,
    productImages: ["https://img001.prntscr.com/file/img001/huSX8RU7Q2i8FZg8PhJffw.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 18
  },
  {
    productTitle: "Zara Satin Effect Dress",
    productBrand: "Zara",
    productSKU: "94792826000",
    productYear: 2024,
    productMaterials: ["Polyester"],
    productDescription: "The Zara Satin Effect Dress offers an elegant and sophisticated look, perfect for special occasions.",
    productCategories: ["Dresses"],
    productSeasons: ["Spring", "Summer"],
    productGenders: ["Women"],
    productColors: ["Black", "Red"],
    productSizes: ["XS", "S", "M", "L"],
    productPrice: 50.00,
    productImages: ["https://img001.prntscr.com/file/img001/ujr9O49YR-2lU_iKZ1gMuA.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 20
  },
  {
    productTitle: "Jack & Jones Basic T-Shirt",
    productBrand: "Jack & Jones",
    productSKU: "12149909",
    productYear: 2024,
    productMaterials: ["Cotton"],
    productDescription: "The Jack & Jones Basic T-Shirt is made from soft cotton and offers a comfortable fit, perfect for everyday wear.",
    productCategories: ["T-Shirts"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["White", "Black", "Grey"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 20.00,
    productImages: ["https://img001.prntscr.com/file/img001/dZy3pDuDRTGIQyauEh9H8Q.jpg", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 30
  },
  {
    productTitle: "Tom Tailor Knitted Sweater",
    productBrand: "Tom Tailor",
    productSKU: "1022252",
    productYear: 2024,
    productMaterials: ["Cotton", "Acrylic"],
    productDescription: "The Tom Tailor Knitted Sweater offers a cozy and stylish look, perfect for cooler weather.",
    productCategories: ["Sweaters"],
    productSeasons: ["Autumn", "Winter"],
    productGenders: ["Women"],
    productColors: ["Beige", "Grey", "Red"],
    productSizes: ["XS", "S", "M", "L"],
    productPrice: 45.00,
    productImages: ["https://img001.prntscr.com/file/img001/N_GE2J3ORVy-uFzSSFGSoA.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 20
  },
  {
    productTitle: "Esprit A-Line Dress",
    productBrand: "Esprit",
    productSKU: "071EE1E302",
    productYear: 2024,
    productMaterials: ["Viscose"],
    productDescription: "The Esprit A-Line Dress offers a flattering silhouette and is perfect for a variety of occasions.",
    productCategories: ["Dresses"],
    productSeasons: ["Spring", "Summer"],
    productGenders: ["Women"],
    productColors: ["Red", "Navy", "Black"],
    productSizes: ["XS", "S", "M", "L"],
    productPrice: 60.00,
    productImages: ["https://img001.prntscr.com/file/img001/GbsXwKWYS5GiJrlSot3cSg.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 20
  },
  {
    productTitle: "Fossil Bifold Leather Wallet",
    productBrand: "Fossil",
    productSKU: "ML3677",
    productYear: 2024,
    productMaterials: ["Leather"],
    productDescription: "The Fossil Bifold Leather Wallet offers a classic design with multiple card slots and a secure bill compartment.",
    productCategories: ["Accessories"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["Brown", "Black"],
    productSizes: ["One Size"],
    productPrice: 40.00,
    productImages: ["https://img001.prntscr.com/file/img001/ItkF74XiTfmDDdq5YIdU1w.jpg", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 25
  },
  {
    productTitle: "H&M Chino Shorts",
    productBrand: "H&M",
    productSKU: "0883696003",
    productYear: 2024,
    productMaterials: ["Cotton"],
    productDescription: "The H&M Chino Shorts offer a comfortable fit and are perfect for warm weather, featuring a classic design.",
    productCategories: ["Shorts"],
    productSeasons: ["Summer"],
    productGenders: ["Men"],
    productColors: ["Beige", "Navy", "Black"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 25.00,
    productImages: ["https://img001.prntscr.com/file/img001/huSX8RU7Q2i8FZg8PhJffw.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 30
  },
  {
    productTitle: "Zara Slim Fit Jeans",
    productBrand: "Zara",
    productSKU: "5065200800",
    productYear: 2024,
    productMaterials: ["Denim"],
    productDescription: "The Zara Slim Fit Jeans offer a modern look with a comfortable fit, made from high-quality denim.",
    productCategories: ["Jeans"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["Blue", "Black"],
    productSizes: ["30", "32", "34", "36", "38"],
    productPrice: 45.00,
    productImages: ["https://img001.prntscr.com/file/img001/ujr9O49YR-2lU_iKZ1gMuA.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 25
  },
  {
    productTitle: "Tom Tailor Casual Shirt",
    productBrand: "Tom Tailor",
    productSKU: "1022054",
    productYear: 2024,
    productMaterials: ["Cotton"],
    productDescription: "The Tom Tailor Casual Shirt offers a relaxed fit and is perfect for everyday wear, made from soft cotton.",
    productCategories: ["Shirts"],
    productSeasons: ["All"],
    productGenders: ["Men"],
    productColors: ["Blue", "White", "Grey"],
    productSizes: ["S", "M", "L", "XL"],
    productPrice: 35.00,
    productImages: ["https://img001.prntscr.com/file/img001/N_GE2J3ORVy-uFzSSFGSoA.png", "https://wstandard.com.my/wp-content/uploads/2020/10/unavailable-image-300x300.jpg"],
    productAvailability: true,
    productStock: 25
  },
]

const createUsers = async () => {
  for (const user of users) {
    const existingUser = await User.findOne({ email: user.email }).exec();
    if (!existingUser) {
      const hashedPassword = await bcrypt.hash(user.password, 10);
      user.password = hashedPassword;
      await User.create(user);
      console.log(`Demo user ${user.email} created successfully.`);
    } else {
      console.log(`Demo user ${user.email} already exists.`);
    }
  }
};

const createProducts = async () => {
  for (const product of products) {
    const existingProduct = await Product.findOne({ productSKU: product.productSKU }).exec();
    if (!existingProduct) {
      await Product.create(product);
      console.log(`Demo product ${product.productSKU} created successfully.`);
    } else {
      console.log(`Demo product ${product.productSKU} already exists.`);
    }
  }
};

const seedDatabase = async () => {
  try {
    await createUsers();
    await createProducts();
  } catch (error) {
    console.error("Error seeding database:", error);
  } finally {
    mongoose.connection.close();
  }
};

seedDatabase();
